### ISSUE TITLE
Hide replies and boosts

### ISSUE THREAD

**Issue by arteteco** [fenwick67/mastofeed#11]
Hi all,
I already wrote it in a toot, but right now I'd like mastofeed to just display my toots, no replies and no boosts. But when there is less than 2 toots in the past 20 feed items, filters are ignored and everything is shown, including boosts and replies.

Would be awesome to just get the past toots, regardless of the number of items in the feed. Just awesome.

**Comment by fenwick67** [comment]
Working on this right now - in the future it will pull more pages in until it fills the window, then pull more as you scroll down. This way it won't have to ignore the filters anymore.

**Comment by fenwick67** [comment]
I just pushed an update and this should be remedied now. Let me know if it's not working for you.
