### ISSUE TITLE
Option to add user's original styles (custom CSS)

### ISSUE THREAD

**Issue by yutarot** [fenwick67/mastofeed#12]
Hi all,
I'd like to ask about the possibility of user's custom CSS.

The actual issue now I have is below.
![screenshot-blog binfish jp-2018 09 29-07-37-14](https://user-images.githubusercontent.com/4077754/46236801-7e4bd600-c3bb-11e8-853e-05f1e7e65672.png)

As you can see, I am a multi-byte language(ja_JP) user and it sometime breaks whitespaces or line breaks depending on its contents.

So first time I just thought to create this issue as just adding something like `.header-right { word-break: break-all; }` though, I realized that it would be annoying for those who using non multi-byte languages such as English.

Also I came to think that it would be nice if we could customize our widget as we like, like changing  colors, fonts, rounding the corners etc.

So here my suggestion is: _adding free text area to enable users to write their own styles_.

But I also can see the point of this, which is how to manage their own styles.

**Comment by fenwick67** [comment]
Thanks for opening the issue.

Is this wrapping better? This is me just applying `word-break: break-word`.  This makes browser try to break at word barriers but break elsewhere if necessary (which is probably better for english too).

![screenshot with new header text](https://user-images.githubusercontent.com/8461973/46251099-322a8100-c40f-11e8-9822-430f1f97ee4b.png)

I'll probably implement the language fix first, then worry about custom styles.

**Comment by yutarot** [comment]
Sure, I agree to have it.
It looks much better than not having it.
Thanks!
