### ISSUE TITLE
Use prefers-color-scheme: dark

### ISSUE THREAD

**Issue by CarlSchwan** [fenwick67/mastofeed#18]
For the moment mastofeed use hardcoded color, I think it would be better to support prefers-color-scheme: dark instead. This would allow mastofeed to work nice with website supporting prefers-color-scheme ;)

![image](https://user-images.githubusercontent.com/23653902/67969805-e04fbe00-fc01-11e9-87d3-762c0528dcd8.png)

**Comment by fenwick67** [comment]
Funny, I was thinking about this the other day. I can work on adding an 'auto' theme that switches based on prefers-color-scheme.

**Comment by fenwick67** [comment]
Just deployed this, use theme `auto`, i.e. `https://www.mastofeed.com/api/feed?url=https%3A%2F%2Fmastodon.technology%2Fusers%2Fkde.atom&theme=auto&size=80&header=true&replies=true&boosts=true` . It will be light unless the user has `prefers-color-scheme: dark`.

**Comment by CarlSchwan** [comment]
Thank you very much for this new feature.

![Screenshot_20191110_224222](https://user-images.githubusercontent.com/23653902/68551294-4fe45b00-0403-11ea-93f0-2f5c7005a1e6.png)

Btw this could need a bit more constrast ;)

**Comment by fenwick67** [comment]
@ognarb Thanks for bringing this up, I agree that doesn't look very good in the screenshot. For me the font looks a lot more readable, I think it's literally a matter of which fonts are installed (I think have Roboto installed which takes precedence in the stylesheet):

![image](https://user-images.githubusercontent.com/8461973/68629937-9f825f80-04b3-11ea-9b1a-31f826f7f1de.png)

I can work on making this more consistent.

**Comment by candidexmedia** [comment]
Hi @fenwick67 : does this app inherit the font/typeface set in the user's website?

**Comment by fenwick67** [comment]
> Hi @fenwick67 : does this app inherit the font/typeface set in the user's website?

No. It's an iframe so it doesn't have access to the parent page's stylesheet
