### ISSUE TITLE
Only showing first toot (repeated on infinite scroll)

### ISSUE THREAD

**Issue by kimberlyxjane** [fenwick67/mastofeed#21]
Hi! Thank you for creating a way to embed my Mastadon posts on my website. I was planning to use it on a site I work on in Neocities. Unfortunately, after embedding it I tried to add more toots, and it's  only showing the first one I posted on an infinite scroll. Am I doing something wrong? Should I fill up my feed before trying to generate the code?

**Comment by fenwick67** [comment]
Can you give me your username and instance URL so I can duplicate? It's normal for new toots to not show up right away, but repeating the same toot infinitely is a bug for sure.

**Comment by kimberlyxjane** [comment]
@liveanddiyinmassachusetts@mstdn.social
What is instance url?

**Comment by fenwick67** [comment]
The instance URL is the part after the last @ symbol, so you've given me all I need. I'll take a look in the next couple of days.

**Comment by fenwick67** [comment]
@kimberlyxjane It is working now. There was a bug if a user didn't have more than a single page of toots. Thanks for pointing this out.

**Comment by kevinpolisano** [comment]
It only shows me the first as well (but without repetition).

instance URL: mathstodon.xyz
username: KevinPolisano
