### ISSUE TITLE
Last feed entry is duplicated infinitely

### ISSUE THREAD

**Issue by inducer** [fenwick67/mastofeed#23]
First of all, thank you for running this service! I use it to embed my feed on my [web page](https://mathema.tician.de/aboutme/). If you scroll to the end of the feed (not hard, I don't have that many posts yet), it keeps adding copies of the same entry. This is not a major issue, but I figured I would let you know.

**Comment by fenwick67** [comment]
Thanks for reporting, I'll see when I can get to it.

**Comment by maphouse** [comment]
I am also having this issue

**Comment by muhme** [comment]
I also have this problem on [heikol.de](https://www.heikol.de). My Mastodon timeline starts on November 13, 2022.
