### ISSUE TITLE
Why render in an iframe?

### ISSUE THREAD

**Issue by enyo** [fenwick67/mastofeed#25]
Is there a reason you're rendering the feed in an iframe and fetch it from your host, instead of exposing the data through a JSON API (or similar) and render it in the client?

**Comment by fenwick67** [comment]
Okay a couple things.

1. I wanted this to work without client-side javascript. Lots of foss fans like mastodon and lots of foss fans like using a javascript whitelist or just turning it off.
2. I'm pretty sure CORS is not enabled on most ActivityPub APIs so the requests would have to be proxied anyways which sucks and then I'd need to figure out a way to make sure people weren't just bouncing requests off my server for general arbitrary JSON CORS proxying.
3. I don't want people to have to drop my javascript onto their domain, then render a bunch of HTML that gets fetched from an untrusted domain (this is just begging for an XSS vulnerability to steal your wordpress cookies).
