### ISSUE TITLE
Hosted version shows 500 server error

### ISSUE THREAD

**Issue by inducer** [fenwick67/mastofeed#32]
Going to https://www.mastofeed.com/ shows me:

![grafik](https://user-images.githubusercontent.com/352067/128646463-cbbd06c3-268b-4c6e-b6dc-77998fd6eac2.png)

(Same happens on my web page, https://andreask.cs.illinois.edu/)

**Comment by calbasi** [comment]
Me too

**Comment by fenwick67** [comment]
Ouch, I'm sorry this is happening.  I'll try and look into it in the next few days, sorry for the late response.

**Comment by fenwick67** [comment]
I know in the past, authorized fetch has spelled trouble for this service, I wonder if it was turned on by default with a recent mastodon update...

**Comment by fenwick67** [comment]
I fixed the issue with the landing page by simply using a domain for the example that doesn't use authorized fetch (mastodon.social).

I'm not going to add authorized fetch support because IDK how that works internally
