### ISSUE TITLE
"trouble fetching posts for this user"

### ISSUE THREAD

**Issue by kimberlyxjane** [fenwick67/mastofeed#37]
I've been unable to generate my new Mastodon's rss feed. I tried a number of different combinations, and I'm certain I have my username and instance correct. Attaching a screen shot of what I entered. 

The error message that appears in the embed (both in the preview and when I just put the code into my website) --
![mastofeed](https://user-images.githubusercontent.com/60074733/163694861-86f82be2-426a-4c20-986e-89d1570456a3.png)

"[500](https://www.mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Ftodon.eu%2Fusers%2F%40lawrencecommunityfridge&theme=dark&size=100&header=false&replies=false&boosts=false#)

Sorry, we are having trouble fetching posts for this user. Please try again later.

If the issue persists, [please open an issue on GitHub](https://github.com/fenwick67/mastofeed/issues), or message fenwick67@octodon.social"

**Comment by andrigamerita** [comment]
@kimberlyxjane Try removing both the protocol string from the beginning of the instance URL (https://, in the screenshot you already did), and also the at symbol (@) from the username.
