### ISSUE TITLE
Error (authorized fetch)

### ISSUE THREAD

**Issue by darmont** [fenwick67/mastofeed#41]
Hi,

Each time I try, I get a 500 error "Sorry, we are having trouble fetching posts for this user. Please try again later."

(Too bad, it was exactly what I needed!)

**Comment by redpandazine** [comment]
Hi,

I have the same problem with the c.im server. Other servers are working. Maybe someone can take a look at it, many thanks!

**Comment by fenwick67** [comment]
> Hi,
> 
> Each time I try, I get a 500 error "Sorry, we are having trouble fetching posts for this user. Please try again later."
> 
> (Too bad, it was exactly what I needed!)

Can you give me your full handle please? (@username@example.com)

**Comment by fenwick67** [comment]
@redpandazine specifically for you it looks like your instance has authorized fetch turned on. Right now I don't have that supported, since it would require me to implement an activitypub actor. Looking at the docs it shouldn't be too hard? (famous last words)

**Comment by fenwick67** [comment]
notes for me: 

https://docs.joinmastodon.org/spec/security/

https://docs.joinmastodon.org/spec/activitypub/#public-key

**Comment by bluelyrah** [comment]
Hello, the same situation seems to be happening with me... my handle is @bluelyrah@mas.to 

edit: my mistake, the problem was that I added "@" to my username, all good now, apologies.

**Comment by ColumbiaView** [comment]
This error has been happening to me for the past few days. I can get to my profile at https://climatejustice.rocks/@CascadiaCAN but the feeds to my webs e.g. https://sallykeely.com/ that one Mastodon feed doesn't work (the other two do). Can you help me troubleshoot this please? ~Sally

**Comment by fenwick67** [comment]
Fixed
