### ISSUE TITLE
Sort toots by language

### ISSUE THREAD

**Issue by gersande** [fenwick67/mastofeed#42]
I have a particular use-case where I have a single account I'd like to create a feed for but I would like to have the option to sort out the post language (so have an embed that only shows English posts, and an embed elsewhere that only sorts for posts in other languages, if they exist). 

It would be very useful! Also thank you so much for this utility, it's very helpful.

**Comment by fenwick67** [comment]
Problem with this is that the API doesn't have a way to query for this. So basically if someone asked for all of Eugen's toots in japanese, I would have to iterate through every single one of his toots. Not really doable, I don't think.
