### ISSUE TITLE
open links within timeline in a new tab

### ISSUE THREAD

**Issue by JJKraw** [fenwick67/mastofeed#43]
Could you create an option so that when a user clicks on a link within an embedded timeline, the page opens in a new tab (target="_blank")? Obviously I can't modify the contents within the frame due to XSS constraints.

Thank you.

**Comment by fenwick67** [comment]
I've added `allow-popups allow-popups-to-escape-sandbox` to the iframe sandbox attribute, so now you should be able to click timeline links, try that and let me know if that doesn't fix your issue.
