### ISSUE TITLE
Enable text compression

### ISSUE THREAD

**Issue by wotnak** [fenwick67/mastofeed#46]
Currently, when running https://pagespeed.web.dev on a site with mastofeed.com embed the following optimization opportunity is reported:
![image](https://user-images.githubusercontent.com/52507690/210202930-c5eb0989-39f8-4903-9976-9ad894ce1963.png)
It would be nice to either:
- implement text compression directly in the application https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression,
- or enable it at the reverse proxy level for mastofeed.com.

**Comment by fenwick67** [comment]
done
