### ISSUE TITLE
Header/cover image stops showing after it is changed by user

### ISSUE THREAD

**Issue by meejle** [fenwick67/mastofeed#57]
Steps to reproduce:

- Generate a Mastofeed iframe for a user
- The user changes their header/cover image on their Mastodon profile
- The header image disappears from Mastofeed
- Generating the iframe again doesn't seem to make any difference
- Neither does clearing my browser cache

I'm specifically having the issue with @CriticalChicken@mastodon.world, but I'm pretty sure I had the issue with my old account before I migrated it, as well. :)

**Comment by fenwick67** [comment]
this might happen because the user data is cached on the server-side for 24h. Looks like it's working for your profile now.
