### ISSUE TITLE
Support Nitter profile RSS feeds

### ISSUE THREAD

**Issue by jo-chemla** [fenwick67/mastofeed#59]
Hi there, 
I tried to replicate my twitter posts to mastodon via mastofeed, ingesting the RSS feed produced by a Nitter instance that supports RSS: https://nitter.poast.org/jo_chemla/with_replies/rss . 
Mastofeed says 
```
🔰 Fetching content from https://rss.app/feeds/gioyjdU3E0t49utq.xml
🚫 Nitter, RSSHub, InoReader and similar feeds are not supported at this time.
```
Same happens for a rss feed built from rss.app that parses a twitter profile.

Will this feature be implemented at some point? 
Thanks a lot for your work, 
Jonathan

**Comment by fenwick67** [comment]
no

**Comment by jo-chemla** [comment]
Sorry I mixed mastofeed.org with mastofeed.com!
