### ISSUE TITLE
Error 500 if I set boosts to true

### ISSUE THREAD

**Issue by paulo-roger** [fenwick67/mastofeed#63]
```html
<iframe allowfullscreen sandbox="allow-top-navigation allow-scripts allow-popups allow-popups-to-escape-sandbox" width="400" height="800" src="https://www.mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fdice.camp%2Fusers%2Fodragaoverde&theme=dark&size=100&header=true&replies=false&boosts=true"></iframe>
```

This is what I am trying.

Though if I set any other configuration with boosts set to false, it works fine.

**Comment by fenwick67** [comment]
just guessing but it's probably authorized fetch failing on the remote profile info. Will check back on this after addressing that

**Comment by fenwick67** [comment]
It had to do with the way Lemmy users were being sent, fixed now

**Comment by paulo-roger** [comment]
Thanks!

**Comment by silksow** [comment]
I'm seeing this issue again:

`<iframe allowfullscreen sandbox="allow-top-navigation allow-scripts allow-popups allow-popups-to-escape-sandbox" src="https://mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fmastodon.social%2Fusers%2Fkylebronsdon&theme=dark&size=100&header=false&replies=false&boosts=true"></iframe>`
