### ISSUE TITLE
wishlist: Mirror resources

### ISSUE THREAD

**Issue by chrysn** [fenwick67/mastofeed#65]
When loading a timeline in the iframe, it references resources from the origin server's CDN (eg. from cdn.fosstodon.org or assets.chaos.social). While these probably have good stability, bandwidth and benign ToS, the loading still requires the operator of a self-hosted mastofeed instance to concern themselves with the CDN's ToS from a privacy (probably also legal) PoV.

I think that it would be a convenient feature for mastofeed to alter URIs that would be loaded automatically (I've only seen image sources, might also be video previews) are rewritten to be local. This may suffice if the local HTTP server is configured to reverse proxy a known set of resources (in a caching fashion, ideally). Even better (but also more complicated on the mastofeed side), the referenced resources could be loaded eagerly when the feed is updated.

**Comment by fenwick67** [comment]
Reverse proxying requests to the CDNs sounds kinda goofy and I don't have the money to keep a media cache on Azure so no not right now
