### ISSUE TITLE
500 Error on Wordpress embed

### ISSUE THREAD

**Issue by MattinNS** [fenwick67/mastofeed#67]
On the page https://matthewguy.com/mastodon/ I started getting an error the last couple of days. Do I need to change something or is it my instance?

<img width="609" alt="Screenshot 2024-04-06 at 10 42 02 AM" src="https://github.com/fenwick67/mastofeed/assets/126929701/5322178c-eac1-4297-88fc-a9705c30e3b2">

**Comment by helenczerski** [comment]
I also have this problem, and it's been two weeks since this was posted with no reply.  I have a Mastodon feed embedded in my Squarespace website, and for the past two weeks it has just shown the same error message as the one above. Before that it was fine. Please can someone help?

**Comment by amenk** [comment]
https://hackers.town/@lmorchard/112634219759756822 suggests this might have to do with the authorized fetch feature.

#68 #69 #70 might be duplicates.

**Comment by giabaio** [comment]
I get this problem too (but it only started a few days ago). Is there any update, please?

**Comment by fenwick67** [comment]
for OP I confirmed it's #41
