### ISSUE TITLE
Error 500 on Cellosaurus.org / cellosaurus@fediscience.org

### ISSUE THREAD

**Issue by evrenkiefer** [fenwick67/mastofeed#68]
Hello,

There is an error 500 on https://www.cellosaurus.org/. The Mastodon account is cellosaurus@fediscience.org. I have determined that if I switch to an account from an other instance, it works. Whereas an other account from the same instance gives me error 500 too. Therefore, **I suspect I've ran into dreaded #41** but I don't know enough about Mastodon to confirm it. Can you tell me how to confirm it? And what is there to do?

Thanks very much for everything,
Kind regards,

Evren

**Comment by fenwick67** [comment]
yep it's #41
