### ISSUE TITLE
500 Error on equestria.social

### ISSUE THREAD

**Issue by Sollace** [fenwick67/mastofeed#69]
Embeds are not working for accounts on https://equestria.social. Initially seemed to be only @projectvinyl but testing with my personal account shows the same error.

Embed code:
```
<iframe allowfullscreen sandbox="allow-top-navigation allow-scripts allow-popups allow-popups-to-escape-sandbox" width="400" height="800" src="https://www.mastofeed.com/apiv2/feed?userurl=https%3A%2F%2Fequestria.social%2Fusers%2Fprojectvinyl&theme=dark&size=100&header=true&replies=false&boosts=false"></iframe>
```
![image](https://github.com/fenwick67/mastofeed/assets/6429283/75a051e3-3c0e-40f1-aaf8-f49583aa3072)

**Comment by MairusuPawa** [comment]
Has the same error. This was fixed by the instance admin today :)

**Comment by Sollace** [comment]
Woohoo! Thanks
