### ISSUE TITLE
Toots with a CW incorrectly displayed

### ISSUE THREAD

**Issue by ghost** [fenwick67/mastofeed#8]
In the Atom feed only the content warning (CW) is displayed, but with Mastofeed only the hidden content is displayed (without CW).

Personally I prefer to show only the CW or the complete toot including the CW. But not like it is now.

**Comment by fenwick67** [comment]
Can you post a dump of the atom feed so I can test against it?

**Comment by ghost** [comment]
https://todon.nl/users/jeroenpraat.atom

The one with a CW is called 'Disgusting nazi's'.

**Comment by fenwick67** [comment]
It's pretty late but CWs work now!

![working content warnings](https://user-images.githubusercontent.com/8461973/46251169-3c4d7f00-c411-11e8-8362-9367e48dcc7d.png)
